medical_warehouse:
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: Strong!password123
      port: 5432
      dbname: medical_db
      schema: analytics
      threads: 4
  target: dev