from fastapi import FastAPI, HTTPException
import psycopg2
from psycopg2.extras import RealDictCursor

app = FastAPI(
    title="Kara Solutions Data Platform API",
    description="Production API endpoints serving transformed medical warehouse telemetry and YOLO detections.",
    version="1.0.0"
)

# Database Connection Parameters (Make sure the password matches yours!)
DB_PARAMS = {
    "host": "localhost",
    "database": "medical_db",
    "user": "postgres",
    "password": "YOUR_ACTUAL_PASSWORD_HERE", # <-- Put your real password here!
    "port": "5432"
}

def get_db_connection():
    """Defensive database connection utility."""
    try:
        conn = psycopg2.connect(**DB_PARAMS, cursor_factory=RealDictCursor)
        return conn
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Database connection fallback failure: {str(e)}")

@app.get("/")
def read_root():
    """Root health-check endpoint."""
    return {
        "status": "online",
        "platform": "Kara Solutions Data Platform",
        "endpoints_available": ["/api/v1/messages", "/api/v1/detections"]
    }

@app.get("/api/v1/messages")
def get_warehouse_messages(limit: int = 50):
    """Fetch structured records directly out of the dbt analytics fact table."""
    conn = get_db_connection()
    cur = conn.cursor()
    try:
        # Querying the dbt-generated fact table defensively
        cur.execute("SELECT * FROM analytics.fct_messages LIMIT %s;", (limit,))
        records = cur.fetchall()
        return {"count": len(records), "data": records}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to query warehouse metrics: {str(e)}")
    finally:
        cur.close()
        conn.close()

@app.get("/api/v1/detections")
def get_yolo_detections(limit: int = 50):
    """Fetch enriched object detection metrics generated by the YOLO engine."""
    conn = get_db_connection()
    cur = conn.cursor()
    try:
        cur.execute("SELECT * FROM raw.enriched_images LIMIT %s;", (limit,))
        records = cur.fetchall()
        return {"count": len(records), "data": records}
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Failed to query ML data: {str(e)}")
    finally:
        cur.close()
        conn.close()